all:
  vars:
    ansible_user: debian
    cluster_name: autoslurm
    slurm_cluster_name: autoslurm
    ansible_ssh_private_key_file: /Users/florentcarli/.ssh/autoslurm_ed25519
    ansible_ssh_common_args: '-o ProxyJump=root@127.0.0.1:2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
    slurm_controller:
      hosts:
        autoslurm-controller-compute-00:
          ansible_host: 172.22.0.170
    slurm_compute:
      hosts:
        autoslurm-controller-compute-00:
          ansible_host: 172.22.0.170
